require('settings')
require('mappings')
require('colorschemes-config.monokaipro')
require('packer-config')
require('nvim-tree-config')
require('feline-config.feline')
require('gitsigns-config')
require('barbar-config')
